sudo: required

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/specification_document/1_1_draft_specs --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /specification_document/1_1_draft_specs/output *.adoc      
  - docker run -v $TRAVIS_BUILD_DIR:/specification_document/1_1_draft_specs --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /specification_document/1_1_draft_specs/output *.adoc    

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:      
  - cd output ; cp -R ../img img
#  - git init
#  - git config user.name "${GH_USER_NAME}"
#  - git config user.email "{GH_USER_EMAIL}"
#  - git add . ; git commit -m "Deploy to GitHub Pages"
#  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1


